// Theme: "Állatok, ételek, tárgyak". hu = accepted Hungarian answers (first one is shown),
// en = the English word. Emoji doubles as the picture.
export const THEME = 'Állatok, ételek, tárgyak';

export const WORDS = [
  { en: 'dog', hu: ['kutya'], emoji: '🐶' },
  { en: 'cat', hu: ['macska'], emoji: '🐱' },
  { en: 'horse', hu: ['ló'], emoji: '🐴' },
  { en: 'cow', hu: ['tehén'], emoji: '🐮' },
  { en: 'pig', hu: ['disznó', 'sertés'], emoji: '🐷' },
  { en: 'fish', hu: ['hal'], emoji: '🐟' },
  { en: 'bird', hu: ['madár'], emoji: '🐦' },
  { en: 'rabbit', hu: ['nyúl'], emoji: '🐰' },
  { en: 'bear', hu: ['medve'], emoji: '🐻' },
  { en: 'lion', hu: ['oroszlán'], emoji: '🦁' },
  { en: 'apple', hu: ['alma'], emoji: '🍎' },
  { en: 'banana', hu: ['banán'], emoji: '🍌' },
  { en: 'bread', hu: ['kenyér'], emoji: '🍞' },
  { en: 'cheese', hu: ['sajt'], emoji: '🧀' },
  { en: 'egg', hu: ['tojás'], emoji: '🥚' },
  { en: 'milk', hu: ['tej'], emoji: '🥛' },
  { en: 'pizza', hu: ['pizza'], emoji: '🍕' },
  { en: 'cake', hu: ['torta'], emoji: '🎂' },
  { en: 'house', hu: ['ház'], emoji: '🏠' },
  { en: 'car', hu: ['autó', 'kocsi'], emoji: '🚗' },
  { en: 'bus', hu: ['busz', 'autóbusz'], emoji: '🚌' },
  { en: 'bike', hu: ['bicikli', 'kerékpár'], emoji: '🚲' },
  { en: 'tree', hu: ['fa'], emoji: '🌳' },
  { en: 'flower', hu: ['virág'], emoji: '🌸' },
  { en: 'sun', hu: ['nap'], emoji: '☀️' },
  { en: 'moon', hu: ['hold'], emoji: '🌙' },
  { en: 'book', hu: ['könyv'], emoji: '📖' },
  { en: 'key', hu: ['kulcs'], emoji: '🔑' },
  { en: 'clock', hu: ['óra'], emoji: '⏰' },
  { en: 'phone', hu: ['telefon'], emoji: '📱' },
];
